-- ============================================================
-- RetailOps Insight
-- SQL Analysis: Sales and Revenue
-- Purpose:
-- Analyze cleaned retail transaction data for revenue,
-- transaction status, monthly trends, countries, and products.
-- ============================================================


-- Query 1: Transaction status summary
-- Business question:
-- How many rows are completed sales, cancelled/returns, or data issues?
SELECT
    transaction_status,
    COUNT(*) AS row_count,
    ROUND(SUM(completed_sales_amount), 2) AS completed_sales_amount,
    ROUND(SUM(cancelled_amount), 2) AS cancelled_amount
FROM transactions
GROUP BY transaction_status
ORDER BY row_count DESC;


-- Query 2: Monthly completed sales trend
-- Business question:
-- How much completed revenue was generated by month?
SELECT
    invoice_year_month,
    COUNT(*) AS completed_transaction_lines,
    ROUND(SUM(completed_sales_amount), 2) AS monthly_completed_sales,
    ROUND(AVG(completed_sales_amount), 2) AS avg_completed_line_value
FROM transactions
WHERE transaction_status = 'Completed'
GROUP BY invoice_year_month
ORDER BY invoice_year_month;


-- Query 3: Top 10 countries by completed sales
-- Business question:
-- Which countries generated the most completed sales?
SELECT
    country,
    COUNT(*) AS completed_transaction_lines,
    ROUND(SUM(completed_sales_amount), 2) AS total_completed_sales
FROM transactions
WHERE transaction_status = 'Completed'
GROUP BY country
ORDER BY total_completed_sales DESC
LIMIT 10;


-- Query 4: Top 10 products by completed sales
-- Business question:
-- Which products generated the most completed sales?
SELECT
    t.stock_code,
    p.product_description,
    COUNT(*) AS completed_transaction_lines,
    SUM(t.quantity) AS units_sold,
    ROUND(SUM(t.completed_sales_amount), 2) AS total_completed_sales
FROM transactions t
LEFT JOIN products p
    ON t.stock_code = p.stock_code
WHERE t.transaction_status = 'Completed'
GROUP BY
    t.stock_code,
    p.product_description
ORDER BY total_completed_sales DESC
LIMIT 10;


-- Query 5: Cancellation/return analysis by month
-- Business question:
-- Which months had the highest cancelled/return amount?
SELECT
    invoice_year_month,
    COUNT(*) AS cancelled_return_lines,
    ROUND(SUM(cancelled_amount), 2) AS total_cancelled_amount
FROM transactions
WHERE transaction_status = 'Cancelled/Return'
GROUP BY invoice_year_month
ORDER BY total_cancelled_amount DESC;


-- Query 6: Data issue summary
-- Business question:
-- How many rows were classified as data issues?
SELECT
    transaction_status,
    COUNT(*) AS issue_row_count,
    ROUND(SUM(line_revenue), 2) AS raw_line_revenue_impact
FROM transactions
WHERE transaction_status = 'Data Issue'
GROUP BY transaction_status;


-- Query 7: Customer coverage summary
-- Business question:
-- How much of the data has known vs missing customer IDs?
SELECT
    CASE
        WHEN customer_id = 'UNKNOWN' THEN 'Missing Customer ID'
        ELSE 'Known Customer ID'
    END AS customer_id_status,
    COUNT(*) AS transaction_lines,
    ROUND(SUM(completed_sales_amount), 2) AS completed_sales_amount
FROM transactions
GROUP BY customer_id_status
ORDER BY transaction_lines DESC;